### ISSUE TITLE
Timezone by default

### ISSUE THREAD

**Issue by sebdraven** [PassiveDNS/PassiveDNS#16]
➜  PassiveDNS git:(master) ✗ sudo docker logs passivedns_api_1
Traceback (most recent call last):
  File "/usr/src/app/./main.py", line 27, in <module>
    config.init_config()
  File "/usr/src/app/utils/config.py", line 8, in init_config
    g = Config()
  File "/usr/src/app/utils/config.py", line 47, in __init__
    self.TIMEZONE = self.get_env_value('TIMEZONE')
  File "/usr/src/app/utils/config.py", line 34, in get_env_value
    raise ConfigEnvError(f"Missing environment variable: {env_name}")

**Comment by sebdraven** [comment]
You have to set env/api.env with variable TIMEZONE

So it's better if this variable don't exist to catch the timezone of OS

**Comment by sebdraven** [comment]
https://github.com/PassiveDNS/PassiveDNS/wiki/Migrate-to-1.0.1-environnement
