### ISSUE TITLE
bug after update a domain by the scheduller

### ISSUE THREAD

**Issue by sebdraven** [PassiveDNS/PassiveDNS#19]
when a domain has update, 

we have an error

91.243.117.248 - - [07/Sep/2021 13:14:51] "GET /resolution/systeminfo.myftp.name/history HTTP/1.1" 200 -
[2021-09-07 13:14:51,847] ERROR in app: Exception on /dn/systeminfo.myftp.name [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 129, in decorator
    return fn(*args, **kwargs)  # pragma: no cover
  File "/usr/src/app/controllers/utils.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/usr/src/app/controllers/domain_name.py", line 223, in manage_domain_name
    return get(domain_name)
  File "/usr/src/app/controllers/domain_name.py", line 123, in get
    resolution = Resolution.get_current_from_domain(dn.domain_name)
  File "/usr/src/app/models/resolution.py", line 149, in get_current_from_domain
    if r.last_updated_at > current.last_updated_at:
TypeError: can't compare offset-naive and offset-aware datetimes

**Comment by sebdraven** [comment]
Ok the problem is with the new timezone: 
![image](https://user-images.githubusercontent.com/1478484/132353920-340fee80-2899-4620-9813-34325f095064.png)

![image](https://user-images.githubusercontent.com/1478484/132353977-8d718927-b655-4549-a7de-002d0ad0b990.png)

**Comment by sebdraven** [comment]
Ok perfect ! https://github.com/PassiveDNS/PassiveDNS/wiki/Migrate-database-older-than-1.0.1 to after the update
