### ISSUE TITLE
Error during the DB initialisation with Docker

### ISSUE THREAD

**Issue by swedishmike** [PassiveDNS/PassiveDNS#5]
Now that I'm actually following the documentation and have used `python db/init.py` I'm getting another error.

During the first `docker-compose up` as I'm setting the environment up the 'db' image fails and crashes out during the initial build. The error reported are as follows:

```
db_1         | Initializing database...Hang on...
db_1         | /entrypoint.sh: running /docker-entrypoint-initdb.d/_init_db.js
db_1         | 2021-07-13T10:07:37Z [262] INFO [99d80] creating user...
db_1         | 2021-07-13T10:07:37Z [262] INFO [99d80] creating database...
db_1         | 2021-07-13T10:07:37Z [262] INFO [99d80] creating collections...
db_1         | 2021-07-13T10:07:37Z [262] INFO [99d80] initializing collections...
db_1         | 2021-07-13T10:07:37Z [262] ERROR [8a210] JavaScript exception in file '/usr/share/arangodb3/js/client/modules/@arangodb/arangosh.js' at 99,7: ArangoError 1221: AQL: illegal document key (while executing)
db_1         | 2021-07-13T10:07:37Z [262] ERROR [409ee] !      throw error;
db_1         | 2021-07-13T10:07:37Z [262] ERROR [cb0bd] !      ^
passivedns_db_1 exited with code 1
```

Subsequent ones errors due to what I guess is the account information etc not having been successfully written into the db as it crashes above.

**Comment by Dadard29** [comment]
Could you please join the content of the file `./db/_init_db_tmp.js` ?

**Comment by swedishmike** [comment]
Sure thing. This is one I just re-created (needed to sanitise out my own info ;) ) and verified that it generates the same error.

Just for version info too:

Python 3.8.10
pycryptodome  3.10.1



[_init_db_tmp.js.zip](https://github.com/PassiveDNS/PassiveDNS/files/6808224/_init_db_tmp.js.zip)

**Comment by Dadard29** [comment]
Try deleting the content of the folder `./db/volume` (not the folder itself). Then, rerun `docker-compose up --build`.

The database image is using volume. As you ran it before, without configuration, it might have caused this issue.

I will add this precision in the documentation

**Comment by swedishmike** [comment]
This happens even after I completely blat my PassiveDNS directory and do a freshj `git pull`.

I have replicated a number of times, including running `docker image rm` on all images etc.

**Comment by swedishmike** [comment]
I've now done the following

- Completely deleted the entire PassiveDNS directory and all subdirectories
- Run a new git clone on the PassiveDNS repo
- Used docker rm/prune to delete all images, containers and volumes
- Copied the _init_db_tmp.js file that is attached to this into the correct location
- Run docker-compose build
- Run docker-compose up

It is now reporting the following from the Scheduler:

```
scheduler_1  | cant connect to the API: 500
scheduler_1  | retrying in 5 seconds...

```

Whereas the api is repeating the following on each retry:

```
api_1        | [2021-07-13 11:54:40,560] ERROR in app: Exception on /login [POST]
api_1        | Traceback (most recent call last):
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
api_1        |     response = self.full_dispatch_request()
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
api_1        |     rv = self.handle_user_exception(e)
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
api_1        |     return cors_after_request(app.make_response(f(*args, **kwargs)))
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
api_1        |     reraise(exc_type, exc_value, tb)
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
api_1        |     raise value
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
api_1        |     rv = self.dispatch_request()
api_1        |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
api_1        |     return self.view_functions[rule.endpoint](**req.view_args)
api_1        |   File "/usr/src/app/controllers/auth.py", line 45, in login
api_1        |     return post()
api_1        |   File "/usr/src/app/controllers/auth.py", line 21, in post
api_1        |     if User.exists_from_email(identity):
api_1        |   File "/usr/src/app/models/user.py", line 140, in exists_from_email
api_1        |     return User._exists_from_key(USER_COLLECTION, "email", email)
api_1        |   File "/usr/src/app/models/meta_node.py", line 125, in _exists_from_key
api_1        |     o = session.exec_aql(f"""
api_1        |   File "/usr/src/app/db/database.py", line 34, in exec_aql
api_1        |     cursor = self._db.aql.execute(aql, bind_vars=bind_vars)
api_1        |   File "/usr/local/lib/python3.9/site-packages/arango/aql.py", line 403, in execute
api_1        |     return self._execute(request, response_handler)
api_1        |   File "/usr/local/lib/python3.9/site-packages/arango/api.py", line 74, in _execute
api_1        |     return self._executor.execute(request, response_handler)
api_1        |   File "/usr/local/lib/python3.9/site-packages/arango/executor.py", line 65, in execute
api_1        |     return response_handler(resp)
api_1        |   File "/usr/local/lib/python3.9/site-packages/arango/aql.py", line 400, in response_handler
api_1        |     raise AQLQueryExecuteError(resp, request)
api_1        | arango.exceptions.AQLQueryExecuteError: [HTTP 401][ERR 11] not authorized to execute this request
api_1        | 172.21.0.2 - - [13/Jul/2021 11:54:40] "POST /login HTTP/1.1" 500 -

```

The database didn't crash out this time though.

Just to check - the _init_db_tmp.js I provided works ok in your end?

**Comment by Dadard29** [comment]
Yes, the `_init_db_tmp.js` file you provided works fine for me

**Comment by Dadard29** [comment]
Ok, if you did reclone the entire projects, you still need to rerun the script `./db/init.py`.

The python script also setup environment files correctly, according to your inputs.

**Comment by swedishmike** [comment]
So a full removal of everything, including volumes/images/containers, git clone and re-run of `./db/init.py` and it's now fully working. Thanks for the help and patience!
